PickC.Internal/Areas/Internal/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

using PickC.Services;
using PickC.Internal.ViewModals;
using PickC.Services.DTO;
using Operation.Contract;
using Operation.BusinessFactory;

namespace PickC.Internal.Areas.Internal.Controllers
{
    [WebAuthFilter]
    [PickCEx]
    public class DashboardController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await GetTripMonitorData());
        }

        [HttpGet]
        public async Task<JsonResult> GetTripMonitorInfo()
        {
            return Json(await GetTripMonitorData(), JsonRequestBehavior.AllowGet);
        }

        public async Task<List<TripMonitorVm>> GetTripMonitorData()
        {
            var tripMonitorList = await new TripMonitorService(AUTHTOKEN, p_mobileNo)
                                            .TripMonitorListAsync();

            var tripMonitorData = new List<TripMonitorVm>();
            if (tripMonitorList != null)
            {
                for (var i = 0; i < tripMonitorList.Count; i++)
                {
                    var tripMonitor = new TripMonitorVm();
                    tripMonitor.address = new Address
                    {
                        address = "",
                        lat = tripMonitorList[i].Latitude,
                        lng = tripMonitorList[i].Longitude,
                    };
                    tripMonitor.title = tripMonitorList[i].DriverID + " - " + tripMonitorList[i].TripID;

                    tripMonitorData.Add(tripMonitor);
                }
            }


            return tripMonitorData;
        }

        public async Task<ActionResult> GetDriversList()
        {
            var driverList = await new DriverService(AUTHTOKEN, p_mobileNo).DriversListAsync();
            var tripMonitor = await GetTripMonitorData();

            var driverMonitorVm = new DriverMonitorVm()
            {
                driverList = driverList,
                tripMonitorVmList = tripMonitor
            };

            return View(driverMonitorVm);
        }

        //[HttpGet]
        //public async Task<ActionResult> CurrentBookings(BookingDTO search)
        //{
        //    var currentbookings = await new SearchService(AUTHTOKEN, p_mobileNo).SearchCurrentBookingAsync(search);
        //    var bookingSearchVM = new BookingSearchDTO();
        //    bookingSearchVM.booking = currentbookings;

        //    return View("CurrentBookings", bookingSearchVM);
        //}
        [HttpGet]
        public async Task<ActionResult> CurrentBookings()
        {
            var currentbookings = await new SearchService(AUTHTOKEN, p_mobileNo).BookingListAsync();
            var bookingSearchVM = new BookingSearchDTO();
            bookingSearchVM.booking = currentbookings;
            return View(bookingSearchVM);
        }
        public async Task<JsonResult> GetCustomerBySearch(int? status)
        {
            var customerlist = await new SearchService(AUTHTOKEN, p_mobileNo).GetCustomerBySearch(status);
            return Json(customerlist, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> CurrentBookings(BookingSearchDTO booking)
        {
            var currentbooking = await new SearchService(AUTHTOKEN, p_mobileNo).SearchBookingByDateAsync(booking);
            var bookingSearchVM = new BookingSearchDTO();
            bookingSearchVM.booking = currentbooking;

            return View("CurrentBookings", bookingSearchVM);

        }
        [HttpGet]
        public async Task<ActionResult> BookingHistory(BookingHistoryDTO search)
        {
            var bookingHistory = await new SearchService(AUTHTOKEN, p_mobileNo).SearchBookingHistoryAsync(search);
            var bookingSearchVM = new BookingHistoryDTO();
            bookingSearchVM.bookingHistory = bookingHistory;
            return View("BookingHistory", bookingSearchVM);
        }
        [HttpPost]
        public async Task<ActionResult> BookingsHistory(BookingHistoryDTO search)
        {
            var bookingHistory = await new SearchService(AUTHTOKEN, p_mobileNo).SearchBookingHistoryAsync(search);
            var bookingSearchVM = new BookingHistoryDTO();
            bookingSearchVM.bookingHistory = bookingHistory;
            return View("BookingHistory", bookingSearchVM);
        }
        [HttpGet]
        public ActionResult UserApp()
        {
            return View("UserApp");
        }
        [HttpGet]
        public ActionResult PaymentHistory()
        {
            return View("PaymentHistory");
        }
        public ActionResult PendingAmount()
        {
            return View("PendingAmount");
        }
        public async Task<JsonResult> GetDriverBySearch(bool? status=null)
        {
          
            var driverlist = await new DriverService(AUTHTOKEN, p_mobileNo).GetDriverBySearch(status);
            return Json(driverlist, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> GetDriverDetails(string id) {
            var driverlist = await new DriverService(AUTHTOKEN, p_mobileNo).DriverInfoAsync(id);
            return Json(driverlist, JsonRequestBehavior.AllowGet);
        }
    }
}

PickC.Internal/Areas/OperatorWeb/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PickC.Internal.Areas.OperatorWeb.Controllers
{
    public class DashBoardController : Controller
    {        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

PickC.Internal/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

using PickC.Services;
using PickC.Internal.ViewModals;

namespace PickC.Internal.Controllers
{
    [WebAuthFilter]
    [PickCEx]
    public class DashboardController :  BaseController
    {        
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await GetTripMonitorData());
        }

        [HttpGet]
        public async Task<JsonResult> GetTripMonitorInfo()
        {
            return Json(await GetTripMonitorData(), JsonRequestBehavior.AllowGet);
        }

        public async Task<List<TripMonitorVm>> GetTripMonitorData()
        {
            var tripMonitorList = await new TripMonitorService(AUTHTOKEN, p_mobileNo)
                                            .TripMonitorListAsync();

            var tripMonitorData = new List<TripMonitorVm>();
            if(tripMonitorList != null)
            {
                for (var i = 0; i < tripMonitorList.Count; i++)
                {
                    var tripMonitor = new TripMonitorVm();
                    tripMonitor.address = new Address
                    {
                        address = "",
                        lat = tripMonitorList[i].Latitude,
                        lng = tripMonitorList[i].Longitude,
                    };
                    tripMonitor.title = tripMonitorList[i].DriverID + " - " + tripMonitorList[i].TripID;

                    tripMonitorData.Add(tripMonitor);
                }
            }
            

            return tripMonitorData;
        }
    }
}

PickC.Internal/Views/Dashboard/BookingHistory.cshtml
@model PickC.Services.DTO.BookingHistoryDTO
@using PickC.Internal.HtmlHelpers
@{
    ViewBag.Title = "BookingHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
     ViewBag.Title = "BookingHistory";
    WebGrid grid = new WebGrid(Model.bookingHistory, rowsPerPage: 10, selectionFieldName: "selectedRow", ajaxUpdateContainerId: "grid");
}
<section class="content">
    @using (Html.BeginForm("BookingsHistory", "Dashboard", FormMethod.Post, new { id = "frmBookingHistory", name = "frmBookingHistory" }))
    {
        <div class="row">
            <div class="col-md-12">
                @{ Html.RenderPartial("DashboardMenuList"); }
                </div> </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="tab-main-content">
                        </div>
                    </div>
                </div>

        <div id="myTabContent" class="tab-content">
                    <div id="tab2" class="tab-pane fade in active">
                        <div class="row" style="margin:10px 0 0 10px;">
                            <div class="col-md-2">
                  @Html.TextBoxFor(x=>x.Datefrom, new { @class = "form-control" })
                       </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(x =>x.DateTo, new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(x =>x.BookingNo, new { @class = "form-control" })
                </div>
                 <div class="col-md-2">
                    @Html.TextBoxFor(x =>x.CustomerMobile, new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <button type="submit" id="btnSearch" class="btn btn-primary" ><i class="fa fa-search"></i>Search </button>
                </div>
            </div>
            </div>
            </div>
                <div class="box-body">
                    @if (Model.bookingHistory.Count != 0)
                {
                        <div class="row">

                            <div class="col-md-12">
                                @grid.Table(
            tableStyle: "table table-hover",
            columns: grid.Columns(
                     @*grid.Column(format: @<text>@Html.ActionLink((string)item.BookingNo,"ActionName","Controllername", new { id = item.id }, null)</text>","Booking No"),*@
                     grid.Column("BookingNo", "Booking No"),
                     grid.Column("CustomerName", "Customer Name"),
                     grid.Column("CustomerMobile", "Customer Mobile"),
                     grid.Column("VehicleNo", "Vehicle No"),
                     grid.Column("DriverName", "Driver Name"),
                     grid.Column("TripFrom", "Trip From"),
                     grid.Column("TripTo", "Trip To"),
                     grid.Column("InvoiceAmount", "Invoice Amount")
                    ),
                 htmlAttributes: new { id = "grid" })
                                </div>
                            </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="pull-right">@grid.PagerList(mode: WebGridPagerModes.All, paginationStyle: "pagination pagination-sm")</div>
                                        </div>
                                    </div>

                        }
                        else
                        {
                            <div>
                                <label>No Data found...</label>
                            </div>
                        }

                    </div>
    }
    </section>
@section secscripts{
<script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script type="text/javascript">
        $(function () {
            $('#bookingHistory').parent().addClass('active');
            $('#DateTo,#Datefrom').datepicker();
            $('#frmBookingHistory').validate({
                rules: {
                    BookingNo: {
                        required: true
                    },
                    CustomerMobile: {
                        required: true
                    }
                }
            });

        });
       
        //function HistorySearch()
        //{
        //    $('#frmBookingHistory').validate();
        //    $('#frmBookingHistory').submit();
        //}
    </script>
}

PickC.Internal/Views/Dashboard/CurrentBookings.cshtml
@model PickC.Services.DTO.BookingSearchDTO
@{
    ViewBag.Title = "CurrentBookings";
    Layout = "~/Areas/Internal/Views/Shared/_Layout.cshtml";
}

<section class="content">
    @using (Html.BeginForm("CurrentBookings", "Dashboard", FormMethod.Post, new { id = "frmCurrentBookings" }))
    {
        <div class="row">
            <div class="col-md-12">
                @{ Html.RenderPartial("DashboardMenuList"); }
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5">
                <label>CurrentBookings</label>
                [@Model.booking.Count]
            </div>
        </div>
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade in active" id="home">
                        <div class="col-md-3">
                            <div class="search-map">
                                <select id="ddlSearchCustomerByStatus" class="form-control">
                                    <option value="0">All</option>
                                    <option value="1">Booking Confirm but Truck No arrived</option>
                                    <option value="2">On going bookings</option>
                                    <option value="3">Truck arrived but Trip Not Started</option>
                                </select>
                            </div>
                            <div class="dr-list" id="CustomerList">
                                <ul class="listofvhl">
                                    @foreach (var item in Model.booking)
                                    {
                                        <li>
                                            <img src="~/images/user_male2-512.png" alt="customer" height="25" style="float:left;" />
                                            <div style="float:left;padding-left:10px;">
                                                <span style="display:block">@item.CustomerName</span>
                                                <span style="display:block"> @item.ReceiverMobileNo</span>
                                                <span style="display:block"> @item.BookingNo</span>
                                            </div>
                                            <div class="clearfix"></div>
                                            <span class="active-dr">
                                                @if (@item.Status == 1)
                                                {
                                                    <i class="fa fa-circle text-danger"></i>
                                                }
                                                @if (@item.Status == 2)
                                                {
                                                    <i class="fa fa-circle text-success"></i>
                                                }
                                                @if (@item.Status == 3)
                                                {
                                                    <i class="fa fa-circle text-warning"></i>
                                                }
                                            </span>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                        @*<div class="row">
                <div class="col-md-12">
                    <div class="tab-main-content">
                        <br />
                        <br />
                        <div class="box">

                            <div class="box-body">
                                <div id="myTabContent" class="tab-content">
                                    <div id="tab2" class="tab-pane fade in active">
                                        <div class="row" style="margin:10px 0 0 10px;">

                                            <div class="col-md-2">
                                                @Html.TextBoxFor(x => x.dates.fromDate, new { @class = "form-control" })
                                                @*<span class="input-group-btn">
                                    <button type="button" class="btn btn-default"><i class="fa fa-calendar" aria-hidden="true"></i></button>
                                </span>*@
                        @*</div>
                                                        <div class="col-md-2">
                                                            @Html.TextBoxFor(x => x.dates.toDate, new { @class = "form-control" })
                                                        </div>
                                                        <div class="col-md-2">
                                                            <button type="submit" id="btnSearch" class="btn btn-primary"><i class="fa fa-search"></i>Search </button>
                                                        </div>
                                                    </div>
                                                    <div class="box-body">
                                                        @if (Model != null)
                                                        {
                                                            <div class="row">

                                                                <div class="col-md-12">
                                                                    @grid.Table(
                tableStyle: "table table-hover",
                columns: grid.Columns(
                     grid.Column("BookingNo", "Booking No"),
                     grid.Column("BookingDate", "Booking Date"),
                     grid.Column("VehicleNo", "Vehicle Number"),
                     grid.Column("CargoType", "Cargo Type")
                    ),
                 htmlAttributes: new { id = "grid" })
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                    <div class="pull-right">@grid.PagerList(mode: WebGridPagerModes.All, paginationStyle: "pagination pagination-sm")</div>
                                                                </div>
                                                            </div>

                                                        }
                                                        else
                                                        {
                                                            <div>
                                                                <label>No Data found...</label>
                                                            </div>
                                                        }

                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>*@
                        }
</section>


@section secscripts{
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dates_fromDate,#dates_toDate').datepicker();
            $('#frmCurrentBookings').validate({
                rules: {
                    'dates.fromDate': {
                        required: true
                    },
                    'dates.toDate': {
                        required: true
                    }
                }
            });
        });
        $(function () {
            $('#currentBookings').parent().addClass('active');

            $('#ddlSearchCustomerByStatus').on("change", function () {
                debugger;
                $.ajax({
                    url: '@Url.Content("~/Internal/Dashboard/GetCustomerBySearch")',
                    method: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    data: JSON.stringify({ 'status': $('#ddlSearchCustomerByStatus').val() }),
                    success: function (data) {
                        $('#CustomerList').val();
                        var html = '';
                        $.each(data, function (key, val) {
                            html += '<ul class="listofvhl">'
                            html += '<li>'
                            html +='<img src="@Url.Content("~/images/user_male2-512.png")" class="img-circle" alt="customer" height="25" style="float:left;">';
                            html += '<div style="float:left;padding-left:10px;">';
                            html += '<span style="display:block"> ' + val.CustomerName + '</span>';
                            html += '<span style="display:block"> ' + val.ReceiverMobileNo + ' </span>';
                            html += '<span style="display:block"> ' + val.BookingNo + ' </span>     </div>';
                            html += '<div class="clearfix"></div>';
                            html += '<span class="active-dr">';
                            if (val.Status == 1) {
                                html += '<i class="fa fa-circle text-danger"></i>';
                            }
                            if (val.Status == 2) {
                                html += '<i class="fa fa-circle text-success"></i>';
                            }
                            if (val.Status == 3) {
                                html += '<i class="fa fa-circle text-warning"></i>';
                            }
                            html += '</span></li></ul>';
                        });

                        $('#CustomerList').html(html);


                    },
                    error: function (err) {

                    },
                    failure: function (fail) {

                    }
                });
            });
        });
    </script>
}

PickC.Internal/Views/Dashboard/Index.cshtml
@model IEnumerable<PickC.Internal.ViewModals.TripMonitorVm>
@{
    ViewBag.Title = "Index";

    var temp = Model;
}
@section seccss{
    <style type="text/css">
        #map {
            height: 380px;
            width: 100%;
            margin: 0px;
            padding: 0px;
        }
    </style>
}
<section class="content">
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>150</h3>
                    <p>Current Bookings</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>53<sup style="font-size: 20px">%</sup></h3>
                    <p>Total Trips</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>44</h3>
                    <p>Loggedin Drivers</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>65</h3>
                    <p>Completed Trips</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="ion ion-ios-people-outline"></i></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="map" style="border: 1px solid rgba(255,255,255,0.15);"></div>
        </div>
    </div>
</section>
@section secscripts{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7WVBL9AmhKs1QAr4x7mArA2mKZY-9nUo&v=3.exp&libraries=places&sensor=true"></script>
    <script type="text/javascript">
        var MapPoints = '@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model))';
        var MY_MAPTYPE_ID = 'custom_style';
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        var map;

        var hyd = new google.maps.LatLng(17.23, 78.27);
        var mapOptions = {
            zoom: 15,
            center: hyd,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        function initialize() {
            directionsDisplay = new google.maps.DirectionsRenderer({ suppressMarkers: true });

            if (jQuery('#map').length > 0) {

                var locations = jQuery.parseJSON(MapPoints);

                map = new google.maps.Map(document.getElementById('map'), {
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    scrollwheel: false
                });
                directionsDisplay.setMap(mapOptions);

                var infowindow = new google.maps.InfoWindow();
                var flightPlanCoordinates = [];
                var bounds = new google.maps.LatLngBounds();

                for (i = 0; i < locations.length; i++) {
                    marker = new google.maps.Marker({
                        position: new google.maps.LatLng(locations[i].address.lat, locations[i].address.lng),
                        map: map,
                        icon: '@Url.Content("~/images/truck.png")'
                    });
                    flightPlanCoordinates.push(marker.getPosition());
                    bounds.extend(marker.position);

                    google.maps.event.addListener(marker, 'click', (function (marker, i) {
                        return function () {
                            infowindow.setContent(locations[i]['title']);
                            infowindow.open(map, marker);
                        }
                    })(marker, i));
                }

                map.fitBounds(bounds);
                /* polyline
                    var flightPath = new google.maps.Polyline({
                        map: map,
                        path: flightPlanCoordinates,
                        strokeColor: "#FF0000",
                        strokeOpacity: 1.0,
                        strokeWeight: 2
                    }); */
                // directions service
                var start = flightPlanCoordinates[0];
                var end = flightPlanCoordinates[flightPlanCoordinates.length - 1];
                var waypts = [];
                for (var i = 1; i < flightPlanCoordinates.length - 1; i++) {
                    waypts.push({
                        location: flightPlanCoordinates[i],
                        stopover: true
                    });
                }
                //calcRoute(start, end, waypts);
            }
        }

        /*
        function calcRoute(start, end, waypts) {
            var request = {
                origin: start,
                destination: end,
                waypoints: waypts,
                optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING
            };
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                    var route = response.routes[0];
                    
                    var summaryPanel = document.getElementById('directions_panel');
                    summaryPanel.innerHTML = '';                    
                    for (var i = 0; i < route.legs.length; i++) {
                        var routeSegment = i + 1;
                        summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment + '</b><br>';
                        summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                        summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                        summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                    }
                }
            });
        }
        */
        google.maps.event.addDomListener(window, 'load', initialize);

        
        $(function () {
            Looping();
        });

        function Looping() {
            setTimeout(function () {
                var promise = GetTripMonitorData();
                $.when(promise).done(function (data) {
                    MapPoints = JSON.stringify(data);
                    initialize();
                    Looping();
                });
            }, 1000 * 60);
        }

        function GetTripMonitorData() {
            var def = $.Deferred();
            $.ajax({
                url: '@Url.Content("~/Dashboard/GetTripMonitorInfo")',
                method: 'GET',
                contentType: 'application/json',
                dataType: 'json',
                success: function (res) {
                    def.resolve(res);
                },
                error: function (err) {
                    def.reject(err);
                },
                failure: function (fail) {
                    def.reject(fail)
                }
            });
            return def.promise();
        }
        
    </script>
}