PickC.Internal/Areas/OperatorWeb/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PickC.Internal.Areas.OperatorWeb.Controllers
{
    public class SupportController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult faq()
        {
            return View();
        }

        [HttpGet]
        public ActionResult addshift()
        {
            return View();
        }
    }
}

PickC.Internal/Areas/OperatorWeb/Views/Support/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/OperatorWeb/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row marginTop">
        <div class="col-md-12 col-xs-12">
            <div class="box box-default box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">Support</h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12 col-xs-12">
                            <ul class="nav nav-pills nav-stacked">
                                <li>
                                    @Html.ActionLink("Shift Management FAQ's", "faq", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Addresses of PickC offices accross the country", "globaloffices", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Troubleshooting the Operator App", "troubleshoot", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Operator App", "operatorapp", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Bookings/Trips", "bookingstrip", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Terms/Agreement", "terms", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    @Html.ActionLink("Account Related", "accountrelated", "Support", null, new { style = "color:#3c8dbc" })
                                </li>
                            </ul>
                        </div>                        
                    </div>
                </div>                
            </div>            
        </div>
    </div>
</div>

PickC.Internal/Areas/OperatorWeb/Views/Support/addshift.cshtml
@{
    ViewBag.Title = "addshift";
    Layout = "~/Areas/OperatorWeb/Views/Shared/_Layout.cshtml";
}

<div class="container">    
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <h4 class="box-title">How do i add a shift ?</h4>
            <h5>
                On the calendar, any car that has no one assigned to it will be
                blank. Simply touch the empty area next to the car and you will take
                to the shift creation screen. Fill in the form to create a new shift.
                All fields are mandatory. If you hit the Dismiss button you will be
                taken back to the original screen with no shift created
            </h5>
        </div>
        <div class="col-md-12 col-xs-12">
            <h4 class="box-title">Related topics</h4>            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <a href="#">Do my driver get alerts/msgs with details of their scheduled shifts ?</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <a href="#">How do i select the days of the week that the driver will work on ?</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <a href="#">I am trying to set a schedule for a driver but i am getting a box that says, "Oops! Driver/Car Conflict".
            What does that mean ?</a>
        </div>
    </div>
</div>

PickC.Internal/Areas/OperatorWeb/Views/Support/faq.cshtml
@{
    ViewBag.Title = "faq";
    Layout = "~/Areas/OperatorWeb/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row marginTop">
        <div class="col-md-12 col-xs-12">
            <div class="box box-default box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">Shift Management FAQs</h3>
                </div>
                <div class="box-body">
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-12 col-xs-12">
                            <ul class="nav nav-pills nav-stacked">
                                <li>
                                    <a href="#">
                                        Can I set a schedule for my drivers?/Is there someplace where i can see the daily timetable of drivers and cars ?
                                    </a>
                                </li>
                                <li>
                                    @Html.ActionLink("How do i add a shift ?", "addshift", null, new { style = "color:#3c8dbc" })
                                </li>
                                <li>
                                    <a href="#">
                                        What does 'Today's calendar' track ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        What are the green boxes on my calendar ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Can i choose a specific car ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        How do i select a specific driver ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Do my driver get alerts/msgs with details of their scheduled shifts ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Will i be alerted in case my drivder does not report on duty ?
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Where do i set the date and timings of the shift ?
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="row">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>